#!/usr/bin/env python3
"""IBM Plex Sans SC / TC / JP / KR のソースフォントを取得する。

PlemoCJK では地域別サブフォントを作るため、IBM Plex Sans の 4 地域版を
ソースとして使う。上流 PlemolJP は JP の TTF をリポジトリにコミットしているが、
4 地域分 (32 ファイル / 約 180MB) をコミットすると重すぎるので、
PlemoCJK で追加する地域分はダウンロード + SHA-256 検証で取得する。

- 取得元は IBM/plex の固定コミット (PLEX_COMMIT) の raw URL
- unhinted TTF のみを使う (ヒンティングは後段の ttfautohint が英数字側に付ける)
- 初回実行時は sources.lock が無いので、ダウンロード結果から生成する
- sources.lock がある場合はハッシュを検証し、不一致ならエラー終了する

Usage:
    python3 fetch_sources.py                 # 取得 + 検証
    python3 fetch_sources.py --update-lock   # sources.lock を作り直す
    python3 fetch_sources.py --check         # ダウンロードせず手元のファイルを検証
    python3 fetch_sources.py --regions SC,KR # 一部の地域だけ取得
"""

from __future__ import annotations

import argparse
import configparser
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# IBM/plex の固定コミット。更新する場合は sources.lock も --update-lock で作り直す。
# git ls-remote https://github.com/IBM/plex.git refs/heads/master
PLEX_COMMIT = "bf260093582f04622aacc1e9f9ca604d7ccd0c42"

RAW_BASE = "https://raw.githubusercontent.com/IBM/plex/{commit}/packages"
# IBM が npm で配っているパッケージは woff/woff2 しか含まないので使わない
URL_TEMPLATE = (
    RAW_BASE + "/plex-sans-{region_lower}/fonts/complete/ttf/unhinted/"
    "IBMPlexSans{region}-{style}.ttf"
)

REGIONS = ("SC", "TC", "JP", "KR")

STYLES = (
    "Thin",
    "ExtraLight",
    "Light",
    "Regular",
    "Text",
    "Medium",
    "SemiBold",
    "Bold",
)

LOCK_PATH = ROOT / "sources.lock"

CHUNK = 1 << 16


def load_settings() -> configparser.ConfigParser:
    settings = configparser.ConfigParser()
    settings.read(ROOT / "build.ini", encoding="utf-8")
    return settings


def source_dir(settings: configparser.ConfigParser, region: str) -> Path:
    """source/IBM-Plex-Sans-XX/unhinted/ を返す"""
    source_fonts_dir = settings.get("DEFAULT", "SOURCE_FONTS_DIR", fallback="source")
    return ROOT / source_fonts_dir / f"IBM-Plex-Sans-{region}" / "unhinted"


def url_for(region: str, style: str) -> str:
    return URL_TEMPLATE.format(
        commit=PLEX_COMMIT,
        region=region,
        region_lower=region.lower(),
        style=style,
    )


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    request = urllib.request.Request(url, headers={"User-Agent": "PlemoCJK-fetch"})
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            if response.status != 200:
                raise RuntimeError(f"HTTP {response.status}")
            with tmp.open("wb") as handle:
                while chunk := response.read(CHUNK):
                    handle.write(chunk)
    except urllib.error.HTTPError as exc:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(f"HTTP {exc.code} for {url}") from exc
    tmp.replace(dest)


def load_lock() -> dict:
    if not LOCK_PATH.is_file():
        return {}
    return json.loads(LOCK_PATH.read_text(encoding="utf-8"))


def write_lock(entries: dict[str, dict[str, str]]) -> None:
    payload = {
        "_comment": (
            "Generated by fetch_sources.py. Keys are paths relative to the "
            "repository root. Run 'python3 fetch_sources.py --update-lock' "
            "after changing PLEX_COMMIT."
        ),
        "plex_commit": PLEX_COMMIT,
        "files": dict(sorted(entries.items())),
    }
    # regen_sc_text.py が書く sc_master_source など、他のスクリプトの記録は残す
    for key, value in load_lock().items():
        payload.setdefault(key, value)
    LOCK_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regions",
        default=",".join(REGIONS),
        help="取得する地域 (カンマ区切り, 既定: SC,TC,JP,KR)",
    )
    parser.add_argument(
        "--update-lock",
        action="store_true",
        help="sources.lock をダウンロード結果で作り直す",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="ダウンロードせず、手元のファイルのハッシュのみ検証する",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="既にファイルがあっても再ダウンロードする",
    )
    args = parser.parse_args()

    regions = [r.strip().upper() for r in args.regions.split(",") if r.strip()]
    unknown = [r for r in regions if r not in REGIONS]
    if unknown:
        print(f"ERROR: unknown region(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    settings = load_settings()
    lock = load_lock()
    locked_files: dict[str, str] = dict(lock.get("files", {}))
    locked_commit = lock.get("plex_commit")

    if locked_commit and locked_commit != PLEX_COMMIT and not args.update_lock:
        print(
            f"ERROR: sources.lock は commit {locked_commit} のものですが、"
            f"fetch_sources.py は {PLEX_COMMIT} を指しています。"
            "--update-lock で作り直してください。",
            file=sys.stderr,
        )
        return 1

    entries: dict[str, str] = {}
    errors: list[str] = []
    downloaded = 0
    verified = 0

    for region in regions:
        directory = source_dir(settings, region)
        for style in STYLES:
            dest = directory / f"IBMPlexSans{region}-{style}.ttf"
            rel = dest.relative_to(ROOT).as_posix()
            url = url_for(region, style)

            if not dest.is_file() or args.force:
                if args.check:
                    errors.append(f"{rel}: missing")
                    continue
                print(f"download {rel}")
                try:
                    download(url, dest)
                except Exception as exc:  # noqa: BLE001 - まとめて報告したい
                    errors.append(f"{rel}: {exc}")
                    continue
                downloaded += 1

            digest = sha256_of(dest)
            entries[rel] = digest

            expected = locked_files.get(rel)
            if expected is None or args.update_lock:
                continue
            if expected != digest:
                errors.append(
                    f"{rel}: sha256 mismatch\n  expected {expected}\n  actual   {digest}"
                )
            else:
                verified += 1

    if errors:
        for message in errors:
            print(f"ERROR: {message}", file=sys.stderr)
        return 1

    if args.update_lock or not LOCK_PATH.is_file():
        merged = {**locked_files, **entries} if not args.update_lock else entries
        # --update-lock で一部地域だけ指定された場合は他地域の記録を残す
        if args.update_lock and set(regions) != set(REGIONS):
            merged = {**locked_files, **entries}
        write_lock(merged)
        print(f"wrote {LOCK_PATH.relative_to(ROOT)} ({len(merged)} files)")

    print(f"downloaded={downloaded} verified={verified} total={len(entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
