#!/usr/bin/env python3
"""Fetch IBM Plex Sans SC / TC / JP / KR source fonts.

PlemoCJK uses all 4 regional variants of IBM Plex Sans to build region-specific
sub-fonts. Upstream PlemolJP commits JP TTFs to the repository, but committing
all 4 regions (32 files / ~180 MB) would be too heavy, so PlemoCJK fetches the
additional regions via download + SHA-256 verification.

- Source is the raw URL at a pinned commit (PLEX_COMMIT) of IBM/plex
- Only unhinted TTFs are used (hinting is applied to the alphanumeric side by ttfautohint later)
- On first run, sources.lock does not exist and is generated from the downloaded files
- If sources.lock exists, hashes are verified; mismatches cause an error exit

Usage:
    python3 fetch_sources.py                 # fetch + verify
    python3 fetch_sources.py --update-lock   # regenerate sources.lock
    python3 fetch_sources.py --check         # verify local files without downloading
    python3 fetch_sources.py --regions SC,KR # fetch specific regions only
"""

from __future__ import annotations

import argparse
import configparser
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Pinned IBM/plex commit. When updating, regenerate sources.lock with --update-lock.
# git ls-remote https://github.com/IBM/plex.git refs/heads/master
PLEX_COMMIT = "bf260093582f04622aacc1e9f9ca604d7ccd0c42"

RAW_BASE = "https://raw.githubusercontent.com/IBM/plex/{commit}/packages"
# IBM's npm packages contain only woff/woff2, so we don't use them
URL_TEMPLATE = (
    RAW_BASE + "/plex-sans-{region_lower}/fonts/complete/ttf/unhinted/"
    "IBMPlexSans{region}-{style}.ttf"
)

REGIONS = ("SC", "TC", "JP", "KR")

STYLES = (
    "Thin",
    "ExtraLight",
    "Light",
    "Regular",
    "Text",
    "Medium",
    "SemiBold",
    "Bold",
)

LOCK_PATH = ROOT / "sources.lock"

CHUNK = 1 << 16


def load_settings() -> configparser.ConfigParser:
    settings = configparser.ConfigParser()
    settings.read(ROOT / "build.ini", encoding="utf-8")
    return settings


def source_dir(settings: configparser.ConfigParser, region: str) -> Path:
    """Return source/IBM-Plex-Sans-XX/unhinted/"""
    source_fonts_dir = settings.get("DEFAULT", "SOURCE_FONTS_DIR", fallback="source")
    return ROOT / source_fonts_dir / f"IBM-Plex-Sans-{region}" / "unhinted"


def url_for(region: str, style: str) -> str:
    return URL_TEMPLATE.format(
        commit=PLEX_COMMIT,
        region=region,
        region_lower=region.lower(),
        style=style,
    )


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    request = urllib.request.Request(url, headers={"User-Agent": "PlemoCJK-fetch"})
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            if response.status != 200:
                raise RuntimeError(f"HTTP {response.status}")
            with tmp.open("wb") as handle:
                while chunk := response.read(CHUNK):
                    handle.write(chunk)
    except urllib.error.HTTPError as exc:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(f"HTTP {exc.code} for {url}") from exc
    tmp.replace(dest)


def load_lock() -> dict:
    if not LOCK_PATH.is_file():
        return {}
    return json.loads(LOCK_PATH.read_text(encoding="utf-8"))


def write_lock(entries: dict[str, dict[str, str]]) -> None:
    payload = {
        "_comment": (
            "Generated by fetch_sources.py. Keys are paths relative to the "
            "repository root. Run 'python3 fetch_sources.py --update-lock' "
            "after changing PLEX_COMMIT."
        ),
        "plex_commit": PLEX_COMMIT,
        "files": dict(sorted(entries.items())),
    }
    # Preserve entries written by other scripts (e.g. sc_master_source from regen_sc_text.py)
    for key, value in load_lock().items():
        payload.setdefault(key, value)
    LOCK_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regions",
        default=",".join(REGIONS),
        help="regions to fetch (comma-separated, default: SC,TC,JP,KR)",
    )
    parser.add_argument(
        "--update-lock",
        action="store_true",
        help="regenerate sources.lock from downloaded files",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify hashes of local files without downloading",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="re-download even if files already exist",
    )
    args = parser.parse_args()

    regions = [r.strip().upper() for r in args.regions.split(",") if r.strip()]
    unknown = [r for r in regions if r not in REGIONS]
    if unknown:
        print(f"ERROR: unknown region(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    settings = load_settings()
    lock = load_lock()
    locked_files: dict[str, str] = dict(lock.get("files", {}))
    locked_commit = lock.get("plex_commit")

    if locked_commit and locked_commit != PLEX_COMMIT and not args.update_lock:
        print(
            f"ERROR: sources.lock was generated for commit {locked_commit}, "
            f"but fetch_sources.py points to {PLEX_COMMIT}. "
            "Run with --update-lock to regenerate.",
            file=sys.stderr,
        )
        return 1

    entries: dict[str, str] = {}
    errors: list[str] = []
    downloaded = 0
    verified = 0

    for region in regions:
        directory = source_dir(settings, region)
        for style in STYLES:
            dest = directory / f"IBMPlexSans{region}-{style}.ttf"
            rel = dest.relative_to(ROOT).as_posix()
            url = url_for(region, style)

            if not dest.is_file() or args.force:
                if args.check:
                    errors.append(f"{rel}: missing")
                    continue
                print(f"download {rel}")
                try:
                    download(url, dest)
                except Exception as exc:  # noqa: BLE001 - collect all errors for batch reporting
                    errors.append(f"{rel}: {exc}")
                    continue
                downloaded += 1

            digest = sha256_of(dest)
            entries[rel] = digest

            expected = locked_files.get(rel)
            if expected is None or args.update_lock:
                continue
            if expected != digest:
                errors.append(
                    f"{rel}: sha256 mismatch\n  expected {expected}\n  actual   {digest}"
                )
            else:
                verified += 1

    if errors:
        for message in errors:
            print(f"ERROR: {message}", file=sys.stderr)
        return 1

    if args.update_lock or not LOCK_PATH.is_file():
        merged = {**locked_files, **entries} if not args.update_lock else entries
        # When --update-lock is used with a subset of regions, preserve other regions' entries
        if args.update_lock and set(regions) != set(REGIONS):
            merged = {**locked_files, **entries}
        write_lock(merged)
        print(f"wrote {LOCK_PATH.relative_to(ROOT)} ({len(merged)} files)")

    print(f"downloaded={downloaded} verified={verified} total={len(entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
